# Generated by Django 3.1.2 on 2020-11-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Project', max_length=100, verbose_name='Title:')),
                ('description', models.CharField(default='Project Description', max_length=100, verbose_name='Description:')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body:')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public:')),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Project', max_length=100, verbose_name='Title:')),
                ('description', models.CharField(default='Project Description', max_length=100, verbose_name='Description:')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_comment', 'User can comment on a chapter'), ('can_edit_self', 'User can edit their own comments'), ('can_edit_other', "User can edit other another user's comment"), ('can_delete_self', 'User can delete their comment'), ('can_delete_other', "User can delete another user's comment")],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
