# Generated by Django 3.1.3 on 2020-11-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201107_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='Project Description', verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='98a5fb63-cdb1-429d-883c-c91c009cf0fb', max_length=100),
        ),
    ]
